tokens:
  - "github token1"
  - "github token2"
org: "some-org"
repos:
  # you can add multiple Repo types
  # where the name could be frontend | backend | mobile | devops
  # names is a list of repo names
  - type: frontend
    names:
      - some-repo-1
  - type: backend
    names:
      - some-repo-2
  - type: mobile
    names:
      - some-repo-3

teams:
  # you can multiple squads different squad
  # each squad is composed of multiple teams
  # supported team names are frontend | backend | mobile | devops
  # if you wish to add more teams please refer to models -> L:9 add new const for new teams
  # team members is an array and the value is there github login
  squad1:
    - name: backend
      members:
        - user1
        - user2
    - name: frontend
      members:
        - user3
        - user4
  squad2:
    - name: mobile
      members:
        - user5
        - user6
    - name: backend
      members:
        - user7
        - user8

